import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import { inspectHevcPps, inspectHevcSps } from '../src/codecs/hevc.ts'
import { decodeHevcIntraPicture } from '../src/codecs/hevc-picture.ts'

const bytes = (base64: string): Uint8Array => Uint8Array.from(Buffer.from(base64, 'base64'))

const pictureHash = (picture: ReturnType<typeof decodeHevcIntraPicture>): string => {
  const sampleBytes = picture.bitDepth === 10 ? 2 : 1
  const output = new Uint8Array(
    (picture.y.length + picture.u.length + picture.v.length) * sampleBytes,
  )
  const view = new DataView(output.buffer)
  let offset = 0
  for (const plane of [picture.y, picture.u, picture.v]) {
    for (const sample of plane) {
      if (sampleBytes === 1) output[offset] = sample
      else view.setUint16(offset, sample, true)
      offset += sampleBytes
    }
  }
  return createHash('sha256').update(output).digest('hex')
}

describe('restricted HEVC intra-picture reconstruction', () => {
  it('exactly reconstructs an independently encoded 8-bit 4:2:0 picture', () => {
    // Generated by x265 4.1 from a 32x32 YUV gradient with SAO, deblocking,
    // WPP, tiles, scaling lists, and CU QP deltas disabled. The expected hash
    // was produced from FFmpeg's decoded planar YUV output.
    const sps = inspectHevcSps(bytes('QgEBBAgAAAMAn6gAAAMAAB6gQghZbp5MLwFoCAAAAwAIAAADAAhA'))
    const pps = inspectHevcPps(bytes('RAHBcYGkgA=='))
    const picture = decodeHevcIntraPicture(bytes('KAGsfOk6FoCJZBiPsF7C3iika9NAeA=='), 20, {
      pps: [pps],
      sps: [sps],
    })
    expect(pictureHash(picture)).toBe(
      'ddde086a6b5565eea61390bd612d5998f358d9232a5ad9d64cf32b238ff7cc81',
    )
    expect(picture).toMatchObject({ width: 32, height: 32, bitDepth: 8, chromaFormat: 1 })
  })

  it('exactly reconstructs an independently encoded Main 10 picture', () => {
    // x265 4.1 encoded this 32x32 testsrc2 picture as limited-range Main 10
    // BT.2020/PQ. FFmpeg produced the expected little-endian planar YUV hash.
    const sps = inspectHevcSps(
      bytes('QgEBAiAAAAMAkAAAAwAAAwAeoEIITZZKuTC8BahIgEggAAADACAAAAMAIQ=='),
    )
    const pps = inspectHevcPps(bytes('RAHBcaGkgA=='))
    const picture = decodeHevcIntraPicture(
      bytes(
        'KAGtwCNGBl0lp1HvS4/wcZzXmuUtHUA/o3vHJ+gpBpIZd4Z+CHeJCRjbOdvpwooNEzM/IT7lyQbvAsDVdVNBshoohnOIjwrH6czmINr7Z7D6aXz//8/gLZglLCknsJowtSw57pL0kg5bOZjl3cbBdXeeBPZpqggAF+UJCTXRNWm1bDnsxe1ByKixfwxXhYTLELSfhtHiaW5SJje21FEBxSoPcnbcxEHNJ4QD0neBRcfW8AlfJRv75+ebNlQ3WZa/vTe+xgRvhJgL90Zkhgo9gImQi5KsH4IitkcwLe4c3RU9Z/WYbAN79wmDWBBjzGiqcJdickqZowHCkSS4ZoKHtxATDbEt28jORaIOhsbMBsJb8pVHrTB5LX28H/olM/kFpNrcjvBnyLd5mGU+LSmLY3i2kMqyXGUkkX9OuU09sej1MdGddXnr/946SB6+23jCV3uwKexwYZNXDsFC8U1ZBjcR2YNmDP5vOTiZv0xVZiYbBQO+C3WbI0R0utTuIRAMsj6GxJyeJEIA+GykmipVv8slhigPo7Bg',
      ),
      20,
      { pps: [pps], sps: [sps] },
    )

    expect(pictureHash(picture)).toBe(
      'b57475d182520e92de78571f145f8921752b8dd139d01c1dfcb9d58a70f20c66',
    )
    expect(picture).toMatchObject({ width: 32, height: 32, bitDepth: 10, chromaFormat: 1 })
  })

  it('exactly reconstructs mixed 8x8 and 4x4 intra coding units', () => {
    // Generated by x265 4.1 from FFmpeg's 16x16 smptebars source at QP 27,
    // with a 16x16 CTU, 8x8 minimum CU, and in-loop filters disabled.
    const sps = inspectHevcSps(bytes('QgEBBAgAAAMAn6gAAAMAAB6giEWW6q8LwFqBAQKCAAADAAIAAAMAMhA='))
    const pps = inspectHevcPps(bytes('RAHBcYGkgA=='))
    const picture = decodeHevcIntraPicture(
      bytes(
        'KAGssGdxpL4vmOELn5LfVzBN52Gd3sqIJAWe1jhXy4qBvBNtLV3k74JomqxyI0R7zW422U3PwQ2QSCrAQDlcC6lBh9GVvtTTWmZKmov8X7nySTquNmH5UmqKL9+KWYtqCHxXFG8XSgmAurYdQtr/74wKX6QWP/8WnNZ8YxXnGuTsGwSMxIxJwCLA',
      ),
      20,
      { pps: [pps], sps: [sps] },
    )

    expect(pictureHash(picture)).toBe(
      'ba1fc796c0522b92f463d9b4867643d627c0f7987a212e5e7deb4b19e8d23e15',
    )
    expect(picture).toMatchObject({ width: 16, height: 16, bitDepth: 8, chromaFormat: 1 })
  })

  it('exactly reconstructs WPP rows with scaling lists and CU QP deltas', () => {
    // x265 4.1 encoded this 128x128 testsrc2 picture using four 32x32 CTB
    // rows, WPP entry points, default scaling lists, 8x8 quantization groups,
    // and CU QP deltas. FFmpeg produced the expected planar YUV hash.
    const sps = inspectHevcSps(bytes('QgEBAWAAAAMAkAAAAwAAAwAeoBAgIFllZrk4XgLQEAAAAwAQAAADAZCA'))
    const pps = inspectHevcPps(bytes('RAHBcvR0kA=='))
    const picture = decodeHevcIntraPicture(
      bytes(
        'KAGscQVUqwHN8V1BlwRNPm6NvJLhhHhcBlFkZOy7Lm3ckKAHPkiLh4PKdG7XZ7vp1r5/dnRI6jvkkJ1Cyl7dv5GEaMD68SrD9iG8eNbXz/ni+vwZ/Y0rxgd0Xavj8B6yXRKJpLqzT9j2IJbDOQA8t//TNt/qFXlLZdYMoAE/x0Ytag+ScMXV0QCwFnv/JNpM76g2+wUysgKVFHo5Q9ptvlQNMZh2v+sJRtuwpbmIpe7u3zBpyUf07YRCIzlK119F/eMrQcqUb0HOwF6DTzBZJcYlfqN8gvTioagN94klzfsxNTf9ULIQycRV5orOomU34y5Mv+AQ9Ag9MkYI5KTWjQ/BD9yKZPdNCT+sSOGRqBpFgOHfHB7bwQ0oZXDyn6D3hm+3EekFzxfNNuyfIIvT6XHItbXEVrXX9dtmfiwPkqrPXfWoWomE3PTZD2LxH5ywLMEk5h5g92k0s6pq6CoAFFdmjjTIZmqj4Ca/YNTKKbRpYzfsyYAPWWfOwgDKNDwKtJIHs2+1V0Olw5RWA/bIIbSlBbmNpwQEd9wEsPRcIncoCefmHZ610S2KKMdo7C3digkYAFS1MoomPDk1lM+zkAxHi+NdMfCRmXpk+ouiA6/ynYLJaBjN/eRlSQuCMxXZr4wZhzeZ9VHGikm1yAJfD9F8yqVugTGKfOQKBuQYnUaiXABXEzUqfKlGnyKbnxOxcT//T/7Ex+3S43+3aDvafoU5bBmmg4hSmB/r5hgcajD9esVOZlIDJ1P3qo1rAUoFRs8dBRNAEMCzMtxcdfBYz09EscN4OjQ5fwECIXUKVXkBZdB5ceZWUVTiL6uCMGtkibdSakf+8uFj7/B1c9zBNR1ox9ZzMOpBObrNtEVcKu8bS380Y2WkjNp9r7vfiCyhF+HQW8sUFj/VSV6+t+I7DfXaiLHYugYpexhhQuWRo1N/rkfvbgqQBGzFyx3tlpR5gd2Grf18eFuDI96La7X9lTZv6emOKNQ8atl2setNBR0Bcj9JeNZXVNQ4mKMdpZF84s6emyjyC3fO+va2NPROfiMmWCO5AJ3OvINWgbdk0IX/+9HPH8nqpa8p4EYPY2a/QAIxV6yaBQ65zygRcJAIUsLFEKkdndc5zWq/JrT/BsYS8YoYffFLVnY+ZT1X3fN7f6N7os0a9gPg7beYD4tTDD1UVWEHjxfiHiP77/uJgSIs+wssPAIXqc8czbRbBCCvKxE4YOmcEQuZ1F7zwRd+djFmde3Fmw7zckENjvCrn6fPezbBohhz6KhC14AWS8O/luRkclR7rQoi5zhVCkhv3tzy7KjCdbEAvZ6ZykIXV05m/ciRbKigbJGvIrPAiHNnngsOzjSrn2SPmhEhwuKDrWgdpAZx+SUeSfgImvMcvoAvvYTlA/NweGuKcuNNcbAfGI5cuHhX5GmAPMvC5T58AE9egaG/POiorAAmjs+nV9a+Xs+fY49FMI4Z1OrsCn/CesxU1Y/axVQK5csulcoWXaG+Sqsmfhhrx8bQ+PBFycnKn+6gPq5bIm7bJAqwsT8IQfS1q8ADCcuHaAjr2xcv+yLpTezSWxvxD9taXo6rlvPkFG1mWzH+jf6DckzuW30aiiro9PS7upGPIHb3spYpTZB0+Z1kDQBdOA9XsbumV23slsPmx0TSLhs+CTU/H+/+au9ncRNW/1VGiyu+a0L3hH1hfdRKJMAx2wuVtw7pJEJxCBBET/0EIBqrtqMU5q4POJmSMtn6jsAAePwvbE4bazFXLEkVfEA+KQQeR9kAo96BESdGAMreQ11bdKz3zI4TuntRQY6dwzWl/8FbL0g+i9BJm6PDnvFm5qjvglSPbA==',
      ),
      20,
      { pps: [pps], sps: [sps] },
    )

    expect(pictureHash(picture)).toBe(
      'b413c309b3a007953c26837f392f4398ee4ab614289ae1dbd253b77fedfe04af',
    )
    expect(picture).toMatchObject({ width: 128, height: 128, bitDepth: 8 })
  })
})
