import { cp, mkdir, readFile, rm, stat } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { build } from 'esbuild'

const sourceDirectory = resolve('docs')
const outputDirectory = resolve('benchmark/.tmp/docs-site')
const demoSource = resolve(sourceDirectory, 'demo.ts')
const legacyBundle = resolve(sourceDirectory, 'assets/demo-app.js')
const outputBundle = join(outputDirectory, 'assets/demo-app.js')

await rm(outputDirectory, { force: true, recursive: true })
await cp(sourceDirectory, outputDirectory, {
  recursive: true,
  filter: (source) => {
    const path = resolve(source)
    return path !== demoSource && path !== legacyBundle
  },
})
await mkdir(dirname(outputBundle), { recursive: true })
await build({
  absWorkingDir: process.cwd(),
  banner: {
    js: '/* Generated by npm run docs:build. Edit docs/demo.ts, not this file. */',
  },
  bundle: true,
  charset: 'utf8',
  entryPoints: ['docs/demo.ts'],
  format: 'esm',
  legalComments: 'none',
  logLevel: 'silent',
  minify: true,
  outfile: outputBundle,
  platform: 'browser',
  sourcemap: false,
  target: ['es2022'],
})

const demoHtml = await readFile(join(outputDirectory, 'demo.html'), 'utf8')
if (!demoHtml.includes('assets/demo-app.js')) {
  throw new Error('Generated docs demo does not reference assets/demo-app.js')
}
const bundle = await stat(outputBundle)
if (bundle.size === 0) throw new Error('Generated docs demo bundle is empty')

console.log(
  `Built GitHub Pages artifact at benchmark/.tmp/docs-site (${bundle.size.toLocaleString()} byte demo bundle)`,
)
