import { copyFile, mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import { build as buildAstro } from 'astro'
import { build } from 'esbuild'
import { generatedScientificFixtures } from '../benchmark/scientific-readers/generated-fixtures.ts'

const sourceDirectory = resolve('docs-astro')
const outputDirectory = resolve('benchmark/.tmp/docs-site')
const outputBundle = join(outputDirectory, 'assets/demo-app.js')
const outputWsiBundle = join(outputDirectory, 'assets/wsi-viewer.js')
const outputWsiWorker = join(outputDirectory, 'assets/wsi-worker.js')
const outputOmeZarrBundle = join(outputDirectory, 'assets/ome-zarr-viewer.js')
const outputOmeZarrWorker = join(outputDirectory, 'assets/ome-zarr-worker.js')
const outputWasm = join(outputDirectory, 'assets/jpeg-decoder.wasm')
const outputSimdDecoderWasm = join(outputDirectory, 'assets/jpeg-decoder-simd.wasm')
const outputEncoderWasm = join(outputDirectory, 'assets/jpeg-encoder.wasm')
const outputSimdEncoderWasm = join(outputDirectory, 'assets/jpeg-encoder-simd.wasm')
const outputPngWasm = join(outputDirectory, 'assets/png-codec.wasm')
const outputSimdPngWasm = join(outputDirectory, 'assets/png-codec-simd.wasm')

await buildAstro({ root: sourceDirectory })

const featureTourFactory = generatedScientificFixtures['ome-zarr-feature-tour-generated']
if (featureTourFactory === undefined) throw new Error('Missing generated OME-Zarr Feature Tour')
const featureTour = featureTourFactory()
const featureTourDirectory = join(outputDirectory, 'fixtures/ome-zarr-feature-tour')
let featureTourBytes = 0
for (const resource of featureTour.resources) {
  const target = join(featureTourDirectory, resource.name)
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, resource.bytes)
  featureTourBytes += resource.bytes.byteLength
}
const maximumFeatureTourBytes = 4 * 1_024 * 1_024
if (featureTourBytes > maximumFeatureTourBytes) {
  throw new Error(
    `Generated OME-Zarr Feature Tour is ${featureTourBytes.toLocaleString()} bytes; expected at most ${maximumFeatureTourBytes.toLocaleString()}`,
  )
}

const builtIndexPages = async (directory: string): Promise<readonly string[]> => {
  const pages: string[] = []
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) pages.push(...(await builtIndexPages(path)))
    else if (entry.name === 'index.html') pages.push(path)
  }
  return pages
}

const sitemapIndex = await readFile(join(outputDirectory, 'sitemap-index.xml'), 'utf8')
if (!sitemapIndex.includes('https://purejsimage.com/sitemap-0.xml')) {
  throw new Error('Generated sitemap index does not reference sitemap-0.xml')
}
const sitemap = await readFile(join(outputDirectory, 'sitemap-0.xml'), 'utf8')
for (const page of await builtIndexPages(outputDirectory)) {
  const directory = dirname(relative(outputDirectory, page)).replaceAll('\\', '/')
  const route = directory === '.' ? '/' : `/${directory}/`
  if (!sitemap.includes(`<loc>https://purejsimage.com${route}</loc>`)) {
    throw new Error(`Generated sitemap omits canonical Astro route ${route}`)
  }
}
if (sitemap.includes('/llms.txt')) throw new Error('Generated sitemap includes non-HTML llms.txt')

await mkdir(dirname(outputBundle), { recursive: true })
const demoBuild = await build({
  absWorkingDir: process.cwd(),
  banner: {
    js: '/* Generated by npm run docs:build. Edit docs-astro/src/scripts/demo.ts, not this file. */',
  },
  bundle: true,
  charset: 'utf8',
  entryPoints: ['docs-astro/src/scripts/demo.ts'],
  format: 'esm',
  legalComments: 'none',
  logLevel: 'silent',
  metafile: true,
  minify: true,
  outfile: outputBundle,
  platform: 'browser',
  sourcemap: false,
  target: ['es2022'],
})
await build({
  absWorkingDir: process.cwd(),
  banner: {
    js: '/* Generated by npm run docs:build. Edit docs-astro/src/scripts/wsi-*.ts, not this file. */',
  },
  bundle: true,
  charset: 'utf8',
  entryPoints: {
    'wsi-viewer': 'docs-astro/src/scripts/wsi-viewer.ts',
    'wsi-worker': 'docs-astro/src/scripts/wsi-worker.ts',
    'ome-zarr-viewer': 'docs-astro/src/scripts/ome-zarr-viewer.ts',
    'ome-zarr-worker': 'docs-astro/src/scripts/ome-zarr-worker.ts',
  },
  entryNames: '[name]',
  format: 'esm',
  legalComments: 'none',
  logLevel: 'silent',
  minify: true,
  outdir: join(outputDirectory, 'assets'),
  platform: 'browser',
  sourcemap: false,
  target: ['es2022'],
})
if (
  Object.keys(demoBuild.metafile.inputs).some(
    (input) =>
      input.endsWith('/codecs/heif.ts') || input.endsWith('/codec-entries/experimental/heic.ts'),
  )
) {
  throw new Error('Default docs demo bundle contains experimental HEIF/HEIC')
}
await copyFile(resolve('src/accelerator-entries/jpeg-decoder.wasm'), outputWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-decoder-simd.wasm'), outputSimdDecoderWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-encoder.wasm'), outputEncoderWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-encoder-simd.wasm'), outputSimdEncoderWasm)
await copyFile(resolve('src/accelerator-entries/png-codec.wasm'), outputPngWasm)
await copyFile(resolve('src/accelerator-entries/png-codec-simd.wasm'), outputSimdPngWasm)

const demoHtml = await readFile(join(outputDirectory, 'demo/index.html'), 'utf8')
if (!demoHtml.includes('assets/demo-app.js')) {
  throw new Error('Generated docs demo does not reference assets/demo-app.js')
}
const bundle = await stat(outputBundle)
if (bundle.size === 0) throw new Error('Generated docs demo bundle is empty')
const wsiBundle = await stat(outputWsiBundle)
const wsiWorker = await stat(outputWsiWorker)
if (wsiBundle.size === 0 || wsiWorker.size === 0) {
  throw new Error('Generated whole-slide viewer bundle is empty')
}
const omeZarrBundle = await stat(outputOmeZarrBundle)
const omeZarrWorker = await stat(outputOmeZarrWorker)
if (omeZarrBundle.size === 0 || omeZarrWorker.size === 0) {
  throw new Error('Generated OME-Zarr viewer bundle is empty')
}
const wasm = await stat(outputWasm)
const simdDecoderWasm = await stat(outputSimdDecoderWasm)
const encoderWasm = await stat(outputEncoderWasm)
const simdEncoderWasm = await stat(outputSimdEncoderWasm)
const pngWasm = await stat(outputPngWasm)
const simdPngWasm = await stat(outputSimdPngWasm)
if (
  wasm.size === 0 ||
  simdDecoderWasm.size === 0 ||
  encoderWasm.size === 0 ||
  simdEncoderWasm.size === 0 ||
  pngWasm.size === 0 ||
  simdPngWasm.size === 0
) {
  throw new Error('Generated docs WASM module is empty')
}

console.log(
  `Built GitHub Pages artifact at benchmark/.tmp/docs-site (${bundle.size.toLocaleString()} byte demo bundle, ${(wsiBundle.size + wsiWorker.size).toLocaleString()} byte WSI viewer, ${(omeZarrBundle.size + omeZarrWorker.size).toLocaleString()} byte OME-Zarr viewer, ${featureTourBytes.toLocaleString()} byte synthetic OME-Zarr Feature Tour, ${(wasm.size + simdDecoderWasm.size + encoderWasm.size + simdEncoderWasm.size + pngWasm.size + simdPngWasm.size).toLocaleString()} bytes of JPEG and PNG WASM modules)`,
)
