import { copyFile, cp, mkdir, readFile, rm, stat } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { build } from 'esbuild'

const sourceDirectory = resolve('docs')
const outputDirectory = resolve('benchmark/.tmp/docs-site')
const demoSource = resolve(sourceDirectory, 'demo.ts')
const legacyBundle = resolve(sourceDirectory, 'assets/demo-app.js')
const outputBundle = join(outputDirectory, 'assets/demo-app.js')
const outputWasm = join(outputDirectory, 'assets/jpeg-decoder.wasm')
const outputSimdDecoderWasm = join(outputDirectory, 'assets/jpeg-decoder-simd.wasm')
const outputEncoderWasm = join(outputDirectory, 'assets/jpeg-encoder.wasm')
const outputSimdEncoderWasm = join(outputDirectory, 'assets/jpeg-encoder-simd.wasm')
const outputPngWasm = join(outputDirectory, 'assets/png-codec.wasm')
const outputSimdPngWasm = join(outputDirectory, 'assets/png-codec-simd.wasm')

await rm(outputDirectory, { force: true, recursive: true })
await cp(sourceDirectory, outputDirectory, {
  recursive: true,
  filter: (source) => {
    const path = resolve(source)
    return path !== demoSource && path !== legacyBundle
  },
})
await mkdir(dirname(outputBundle), { recursive: true })
const demoBuild = await build({
  absWorkingDir: process.cwd(),
  banner: {
    js: '/* Generated by npm run docs:build. Edit docs/demo.ts, not this file. */',
  },
  bundle: true,
  charset: 'utf8',
  entryPoints: ['docs/demo.ts'],
  format: 'esm',
  legalComments: 'none',
  logLevel: 'silent',
  metafile: true,
  minify: true,
  outfile: outputBundle,
  platform: 'browser',
  sourcemap: false,
  target: ['es2022'],
})
if (
  Object.keys(demoBuild.metafile.inputs).some(
    (input) =>
      input.endsWith('/codecs/heif.ts') || input.endsWith('/codec-entries/experimental/heic.ts'),
  )
) {
  throw new Error('Default docs demo bundle contains experimental HEIF/HEIC')
}
await copyFile(resolve('src/accelerator-entries/jpeg-decoder.wasm'), outputWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-decoder-simd.wasm'), outputSimdDecoderWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-encoder.wasm'), outputEncoderWasm)
await copyFile(resolve('src/accelerator-entries/jpeg-encoder-simd.wasm'), outputSimdEncoderWasm)
await copyFile(resolve('src/accelerator-entries/png-codec.wasm'), outputPngWasm)
await copyFile(resolve('src/accelerator-entries/png-codec-simd.wasm'), outputSimdPngWasm)

const demoHtml = await readFile(join(outputDirectory, 'demo.html'), 'utf8')
if (!demoHtml.includes('assets/demo-app.js')) {
  throw new Error('Generated docs demo does not reference assets/demo-app.js')
}
const bundle = await stat(outputBundle)
if (bundle.size === 0) throw new Error('Generated docs demo bundle is empty')
const wasm = await stat(outputWasm)
const simdDecoderWasm = await stat(outputSimdDecoderWasm)
const encoderWasm = await stat(outputEncoderWasm)
const simdEncoderWasm = await stat(outputSimdEncoderWasm)
const pngWasm = await stat(outputPngWasm)
const simdPngWasm = await stat(outputSimdPngWasm)
if (
  wasm.size === 0 ||
  simdDecoderWasm.size === 0 ||
  encoderWasm.size === 0 ||
  simdEncoderWasm.size === 0 ||
  pngWasm.size === 0 ||
  simdPngWasm.size === 0
) {
  throw new Error('Generated docs WASM module is empty')
}

console.log(
  `Built GitHub Pages artifact at benchmark/.tmp/docs-site (${bundle.size.toLocaleString()} byte demo bundle, ${(wasm.size + simdDecoderWasm.size + encoderWasm.size + simdEncoderWasm.size + pngWasm.size + simdPngWasm.size).toLocaleString()} bytes of JPEG and PNG WASM modules)`,
)
