export type {
  AnalysisResult,
  AnalysisResultLimits,
  AnalysisResultSummary,
  BooleanTableColumn,
  CategoryTableColumn,
  HistogramCountArray,
  HistogramResult,
  NumericTableColumn,
  ProfileAxis,
  ProfileResult,
  ProfileSeries,
  ResolvedAnalysisResultLimits,
  ResultCategoryCodes,
  ResultCollection,
  ResultCollectionEntry,
  ResultMemoryAccounting,
  ResultNaNPolicy,
  ResultNumericArray,
  ResultProvenanceReference,
  ResultSummaryOptions,
  ResultValidityBitmap,
  ScalarResult,
  TableColumn,
  TableResult,
  Utf8TableColumn,
} from './result.ts'
export {
  accountAnalysisResultMemory,
  analysisResultSchemas,
  analysisResultValueTypeDefinitions,
  analysisResultValueTypeDescriptors,
  createAnalysisResultValueTypeRegistry,
  defaultAnalysisResultLimits,
  histogramResultValueTypeId,
  profileResultValueTypeId,
  resolveAnalysisResultLimits,
  resultCollectionValueTypeId,
  scalarResultValueTypeId,
  summarizeResult,
  tableResultValueTypeId,
  validateAnalysisResult,
  validateHistogramResult,
  validateProfileResult,
  validateResultCollection,
  validateScalarResult,
  validateTableResult,
} from './result.ts'
export type {
  ScientificMeasurementResultOptions,
  ScientificPlaneAnalysis,
} from './scientific.ts'
export {
  measureScientificPlaneWithResults,
  scientificPlaneMeasurementToResult,
} from './scientific.ts'
